repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    - id: end-of-file-fixer
      exclude: ^.example/
    - id: trailing-whitespace
      exclude: ^.example/
    - id: check-yaml

  - repo: https://github.com/psf/black
    rev: '24.4.2'
    hooks:
      - id: black
        name: Python Black
        args: ["--line-length", "79"]

  - repo: https://github.com/pycqa/flake8
    rev: '7.1.0'
    hooks:
    - id: flake8

  - repo: https://github.com/jvllmr/poetry-types
    rev: v0.5.1
    hooks:
      - id: poetry-types

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.0'
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-flake8"
          - "types-requests"
          - "types-pyyaml"
